version: '3'
services:
  web:
    build: ./apps
    ports:
      - "5300:5300"
    restart: unless-stopped
    volumes:
      - ./templates:/templates
  nginx:
    image: nginx:latest
    ports:
      - "5200:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
