version: '3'
services:
  web:
    build: ./apps
    ports:
      - "5000:5000"
  nginx:
    image: nginx:latest
    ports:
      - "5200:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
